name: Build code by calling reusable build workflow TEMPLATE

on:
 workflow_dispatch:
      
jobs:
  call-build-reusable-workflow-from-shared-repo:                                      # Call Reusable Workflow located in Shared Repo
    uses: ljupcokostoski/shared-workflows/.github/workflows/reusable-build.yml@main   # Reusable Workflow file
    with:                                                                             # Reusable Workflow entry parameters
      project-name: RESTfulWebAPI
      dotnet-version: '6'
    secrets:                                                                          # Reusable Workflow secrets
      connection-guid: '88daa56d-0c87-494e-8bf6-a06a1310144f'      
